import {IBuilderBaseConfig, IBuilderConfig, IBuilderFilter} from "./Builder";

export type IGridBuilder = IBuilderBaseConfig & {
    autoload?: "false" | "true",
    btnrefresh?: "false" | "true",
    btnaudit?: "false" | "true",
    btndelete?: "false" | "true",
    btnexcel?: "false" | "true",
    columns: IBuilderConfig[],
    childwindow: any[],
    ckQuery?: string,
    ckPageObject: string,
    ckMaster?: string,
    excelname?: string,
    pagesize?: number,
    topbtn?: any[],
    orderdirection: string,
    orderproperty: string,
    filters?: IBuilderFilter[],
    height?: string,
    contextmenus?: any[],
    hideactions?: "false" | "true",
    column?: string,
    valuefield?: string,
    rootvisible?: string,
    winreloadstores?: "true" | "false",
    collectionvalues?: "object" | "array",
    reloadmaster?: "false" | "true",
    selmode?: "SINGLE" | "SIMPLE" | "MULTI",
    collapsed?: "true" | "false",
    autoselectidentity?: string,
    stepnamenext?: string,
    detail?: IBuilderBaseConfig[],
};
