// @flow
import {mergeComponents} from "../../utils/builder";
import {type BuilderFieldType} from "../../TextField/BuilderFieldType";

export const getAreaFieldConfig = (bc: BuilderFieldType) => ({
    ckPageObject: `area_${bc.ckPageObject}`,
    ckQuery: "jNSIGetAddrArea",
    clearfield: "ck_street,ck_house",
    column: "ck_area",
    cvDisplayed: "Населенный пункт",
    datatype: "combo",
    disabledrules: `!g_${bc.ckPageObject}_ck_region`,
    displayfield: "cv_area",
    getglobaltostore: `g_${bc.ckPageObject}_ck_region=ck_region`,
    minchars: "4",
    noglobalmask: "true",
    querydelay: "1",
    querymode: "remote",
    queryparam: "cv_area",
    reloadfield: `mo_${bc.ckPageObject}`,
    required: "true",
    selfclean: "true",
    setglobal: `g_${bc.ckPageObject}_ck_area,g_${bc.ckPageObject}_ck_master`,
    type: "IFIELD",
    valuefield: "ck_area",
});

export const getRegionFieldConfig = (bc: BuilderFieldType) => ({
    ckPageObject: `region_${bc.ckPageObject}`,
    ckQuery: "jNSIGetAddrRegion",
    clearfield: "ck_area,ck_street,ck_house",
    column: "ck_region",
    cvDisplayed: "Регион",
    datatype: "combo",
    displayfield: "cv_region",
    minchars: "4",
    noglobalmask: "true",
    querydelay: "1",
    querymode: "remote",
    queryparam: "cv_region",
    reloadfield: `mo_${bc.ckPageObject}`,
    required: "true",
    selfclean: "true",
    setglobal: `g_${bc.ckPageObject}_ck_region`,
    type: "IFIELD",
    valuefield: "ck_region",
});

export const getStreetFieldConfig = (bc: BuilderFieldType) => ({
    ckPageObject: `street_${bc.ckPageObject}`,
    ckQuery: "jNSIGetAddrStreet",
    clearfield: "ck_house",
    column: "ck_street",
    cvDisplayed: "Улица",
    datatype: "combo",
    disabledrules: `!g_${bc.ckPageObject}_ck_area`,
    displayfield: "cv_street",
    getglobaltostore: [`g_${bc.ckPageObject}_ck_area=ck_area`, `g_${bc.ckPageObject}_ck_region=ck_region`].join(","),
    minchars: "4",
    noglobalmask: "true",
    querydelay: "1",
    querymode: "remote",
    queryparam: "cv_street",
    reloadfield: `mo_${bc.ckPageObject}`,
    selfclean: "true",
    setglobal: `g_${bc.ckPageObject}_ck_street,g_${bc.ckPageObject}_ck_master`,
    type: "IFIELD",
    valuefield: "ck_street",
});

export const getHouseFieldConfig = (bc: BuilderFieldType) => ({
    ckPageObject: `house_${bc.ckPageObject}`,
    ckQuery: "jNSIGetAddrHouse",
    column: "ck_house",
    cvDisplayed: "Дом",
    datatype: "combo",
    disabledrules: `!g_${bc.ckPageObject}_ck_area`,
    displayfield: "cv_house",
    getglobaltostore: [
        `g_${bc.ckPageObject}_ck_area=ck_area`,
        `g_${bc.ckPageObject}_ck_street=ck_street`,
        `g_${bc.ckPageObject}_ck_region=ck_region`,
    ].join(","),
    minchars: "1",
    noglobalmask: "true",
    querydelay: "1",
    querymode: "remote",
    queryparam: "cv_house",
    reloadfield: `mo_${bc.ckPageObject}`,
    selfclean: "true",
    setglobal: `g_${bc.ckPageObject}_ck_master`,
    type: "IFIELD",
    valuefield: "ck_house",
});

export const getMoFieldConfig = (bc: BuilderFieldType) => ({
    autoload: "false",
    ckDEndpoint: bc.ckDEndpoint,
    ckMaster: `house_${bc.ckPageObject}`,
    ckPageObject: `mo_${bc.ckPageObject}`,
    ckQuery: "MOShowMOsByAddress",
    column: "ck_id",
    cvDisplayed: "Наименование объекта обслуживания",
    datatype: "combo",
    disabledrules: `!g_${bc.ckPageObject}_ck_area`,
    displayfield: "cv_name",
    idproperty: `ck_id=g_${bc.ckPageObject}_ck_master`,
    minchars: "0",
    noglobalmask: "true",
    querydelay: "1",
    querymode: "remote",
    queryparam: "cv_name",
    required: "true",
    selfclean: "true",
    type: "IFIELD",
    valuefield: "ck_id",
});

export const getMoMultiFieldConfig = (bc: BuilderFieldType) => {
    const {overrides} = mergeComponents(
        bc.childs,
        {
            "Override Area Field": getAreaFieldConfig(bc),
            "Override House Field": getHouseFieldConfig(bc),
            "Override Mo Field": getMoFieldConfig(bc),
            "Override Region Field": getRegionFieldConfig(bc),
            "Override Street Field": getStreetFieldConfig(bc),
        },
        {
            exclude: [
                "disabledrules",
                "disabled",
                "hidden",
                "hiddenrules",
                "getglobaltostore",
                "reloadfield",
                "setglobal",
                "column",
                "selfclean",
                "datatype",
            ],
            include: [
                "defaultvalue",
                "defaultvaluequery",
                "pagesize",
                "minchars",
                "info",
                "querydelay",
                "displayfield",
                "getglobal",
            ],
        },
    );

    return [
        overrides["Override Region Field"],
        overrides["Override Area Field"],
        overrides["Override Street Field"],
        overrides["Override House Field"],
        overrides["Override Mo Field"],
    ];
};
