// @flow
import {type BuilderModeType} from "../../BuilderType";

export type ButtonConfigType = {
    modeaction?: string,
    cv_displayed: string,
    cn_order?: number,
    ck_page_object: string,
    ck_master?: string,
    extraplugingate?: string,
    filemode?: "single" | "multi",
    filetypes?: string,
    iconfont?: string,
    iconsize?: "xs" | "lg" | "2x" | "3x" | "4x" | "5x",
    ck_parent?: string,
    handler?: string,
    maxfile?: string,
    mode?: BuilderModeType,
    uitype?: string,
    tipmsg?: string,
    confirmquestion?: string,
    confirmquestionposition?: "right" | "top",
    onlyicon?: "true" | "false",
    readonly?: "true" | "false",
    iconfontname?: "fa" | "mdi",
    handlerFn?: () => void,
    updatequery?: string,
    topbtn?: Array<ButtonConfigType>,
    btncollectorall?: "true" | "false",
    redirecturl?: string,
    redirectusequery?: string,
    columnsfilter?: string,
    timeout?: string,
    type: string,
};
